---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: "PA VPC master stack"
  Metadata: {}

  Parameters:
    # Specify CIDR for new VPC
    pVPCNAME:
      Description: Name tag for the VPC (i.e. Prd, Dev, POC)
      Type: String
      Default: pa-vpc

  Mappings: {}

  Conditions: {}

  Resources: 
      stackVPC:
        Type: AWS::CloudFormation::Stack
        Properties:
          TemplateURL: https://birender-pa-bucket-test.s3.ap-south-1.amazonaws.com/vpc.yaml
          Parameters:
            pVPCNAME:
              Ref: pVPCNAME
               

      stackEIP:
        Type: AWS::CloudFormation::Stack
        DependsOn: 
        - stackVPC
        Properties:
          TemplateURL: https://birender-pa-bucket-test.s3.ap-south-1.amazonaws.com/eip.yaml
          Parameters:
            pVPCNAME:
              Ref: pVPCNAME

      stackSUBNET:
        Type: AWS::CloudFormation::Stack
        DependsOn: 
        - stackVPC
        Properties:
          TemplateURL: https://birender-pa-bucket-test.s3.ap-south-1.amazonaws.com/subnet.yaml
          Parameters:
            pVPCNAME:
              Ref: pVPCNAME

      stackIGW:
        Type: AWS::CloudFormation::Stack
        DependsOn: 
        - stackVPC
        Properties:
          TemplateURL: https://birender-pa-bucket-test.s3.ap-south-1.amazonaws.com/igw.yaml
          Parameters:
            pVPCNAME:
              Ref: pVPCNAME

      stackNATGW:
        Type: AWS::CloudFormation::Stack
        DependsOn: 
        - stackIGW
        - stackEIP
        - stackSUBNET
        Properties:
          TemplateURL: https://birender-pa-bucket-test.s3.ap-south-1.amazonaws.com/ngw.yaml
          Parameters:
            pVPCNAME:
              Ref: pVPCNAME

      stackROUTES:
        Type: AWS::CloudFormation::Stack
        DependsOn: 
        - stackIGW
        - stackNATGW
        - stackSUBNET
        - stackVPC
        Properties:
          TemplateURL: https://birender-pa-bucket-test.s3.ap-south-1.amazonaws.com/route.yaml
          Parameters:
            pVPCNAME:
              Ref: pVPCNAME

      stackSECURITYGROUP:
        Type: AWS::CloudFormation::Stack
        DependsOn: 
        - stackVPC
        Properties:
          TemplateURL: https://birender-pa-bucket-test.s3.ap-south-1.amazonaws.com/sg.yaml
          Parameters:
            pVPCNAME:
              Ref: pVPCNAME       
              
      stackEKS:
        Type: AWS::CloudFormation::Stack
        DependsOn: 
        - stackROUTES
        Properties:
          TemplateURL: https://birender-pa-bucket-test.s3.ap-south-1.amazonaws.com/eks.yaml
          Parameters:
            pVPCNAME:
              Ref: pVPCNAME              
               
